######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 17 12:20:09 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += processImage.h videodevice.h
SOURCES += main.cpp processImage.cpp videodevice.cpp
